import puppeteer from "puppeteer";


export async function generatePdf(): Promise<Uint8Array> {
	const browser = await puppeteer.launch({ headless: true });

	try {
		const page = await browser.newPage();

		await page.setContent(`
			<html>
				<body>
					<h1>Test PDF</h1>
					<p>This is generated by Deno.</p>
				</body>
			</html>
		`);

		const buffer = await page.pdf({
			format: "A4",
			printBackground: true,
		});

		return new Uint8Array(buffer);
	} finally {
		await browser.close();
	}
}

/*export async function handler(req: Request): Promise<Response> {
	const browser = await puppeteer.launch({
		headless: true,
		args: ["--no-sandbox"]
	});

	try {
		const page = await browser.newPage();

		// Example dynamic content
		const html = `
		<html>
		<head>
			<style>
				body {
					font-family: Arial;
					padding: 40px;
				}

				h1 {
					color: #333;
				}

				.highlight {
					color: blue;
					font-weight: bold;
				}
			</style>
		</head>

		<body>
			<h1>Dynamic PDF</h1>
			<p>This is dynamically generated.</p>
			<p class="highlight">Formatting is preserved.</p>
		</body>
		</html>
		`;

		await page.setContent(html, {
			waitUntil: "networkidle0"
		});

		const pdf = await page.pdf({
			format: "A4",
			printBackground: true
		});

		return new Response(pdf, {
			headers: {
				"Content-Type": "application/pdf",
				"Content-Disposition":
					'attachment; filename="document.pdf"',
			},
		});
	} finally {
		await browser.close();
	}
}*/